# Generated by Django 4.2.2 on 2023-06-25 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='choice date'),
            preserve_default=False,
        ),
    ]
